using System.Text.Json;

namespace Gaep.HostClient;

internal static partial class PortableDesignProtocol
{
    private const string ApprovedFigmaContextRetrievalProjectionPrivacyBoundary =
        "projection-contains-record-identities-versions-counts-states-and-receipt-digests-only-not-design-or-source-content-prompts-provider-output-machine-paths-personal-data-secrets-credentials-or-permissions";
    private const string ApprovedFigmaContextRetrievalProjectionAuthorityBoundary =
        "approved-figma-context-retrieval-projection-is-read-only-and-grants-no-figma-access-content-materialization-context-transfer-generation-provider-stage-mutation-approval-authorization-acceptance-release-deployment-or-action-authority";
    private const string ApprovedFigmaContextRetrievalStatusAuthorityBoundary =
        "approved-figma-context-retrieval-status-is-observational-and-grants-no-figma-access-content-materialization-context-transfer-generation-provider-stage-mutation-approval-authorization-acceptance-release-deployment-or-action-authority";

    internal static ApprovedFigmaContextRetrievalProjection ParseApprovedFigmaContextRetrievalResponse(JsonElement envelope, Guid expectedInitiativeId)
    {
        var projection = ReadResult(envelope);
        if (!HasRequiredAndAllowedProperties(projection, ["schemaVersion", "kind", "product", "initiative", "status", "observedAt", "privacyBoundary", "authorityBoundary", "snapshotDigest"], ["candidate"]) ||
            ParseBoundedNonNegativeInt(projection, "schemaVersion", 1) != 1 || ParseRequiredEnum(projection, "kind", "approved-figma-context-retrieval-projection") != "approved-figma-context-retrieval-projection" ||
            ParseRequiredEnum(projection, "privacyBoundary", ApprovedFigmaContextRetrievalProjectionPrivacyBoundary) != ApprovedFigmaContextRetrievalProjectionPrivacyBoundary ||
            ParseRequiredEnum(projection, "authorityBoundary", ApprovedFigmaContextRetrievalProjectionAuthorityBoundary) != ApprovedFigmaContextRetrievalProjectionAuthorityBoundary) throw InvalidResponse();
        var snapshotDigest = ParseRequiredDigest(projection, "snapshotDigest"); if (snapshotDigest != CanonicalDigest(WithoutProperty(projection, "snapshotDigest"))) throw InvalidResponse();
        var product = projection.GetProperty("product"); if (!HasOnlyProperties(product, "id", "revision", "digest")) throw InvalidResponse();
        var productId = ParseRequiredGuid(product, "id"); var productRevision = ParsePositiveLong(product, "revision"); var productDigest = ParseRequiredDigest(product, "digest");
        var initiative = projection.GetProperty("initiative"); if (!HasOnlyProperties(initiative, "id", "revision", "digest", "state")) throw InvalidResponse();
        var initiativeId = ParseRequiredGuid(initiative, "id"); if (initiativeId != expectedInitiativeId) throw InvalidResponse();
        var initiativeRevision = ParsePositiveLong(initiative, "revision"); var initiativeDigest = ParseRequiredDigest(initiative, "digest"); var initiativeState = ParseRequiredEnum(initiative, "state", "proposed", "active", "blocked", "completed", "cancelled");
        string[] counts = ["snapshotItemCount", "includedItemCount", "requirementBindingCount", "designToCodeBindingCount", "routeSubjectCount", "implementationUnitCount", "pathCount", "staleBindingCount", "snapshotGapCount", "generationContextGapCount", "lifecycleGapCount", "evidenceGapCount", "invalidCandidateCount", "unresolvedQuestionCount"];
        var status = projection.GetProperty("status");
        if (!HasRequiredAndAllowedProperties(status, ["schemaVersion", "kind", "productId", "productRevision", "initiativeId", "initiativeRevision", .. counts, "reviewState", "state", "reasons", "assessedAt", "authorityBoundary"], ["candidate", "dependencies"]) ||
            ParseBoundedNonNegativeInt(status, "schemaVersion", 1) != 1 || ParseRequiredEnum(status, "kind", "approved-figma-context-retrieval-status") != "approved-figma-context-retrieval-status" ||
            ParseRequiredGuid(status, "productId") != productId || ParsePositiveLong(status, "productRevision") != productRevision || ParseRequiredGuid(status, "initiativeId") != initiativeId || ParsePositiveLong(status, "initiativeRevision") != initiativeRevision ||
            ParseRequiredEnum(status, "authorityBoundary", ApprovedFigmaContextRetrievalStatusAuthorityBoundary) != ApprovedFigmaContextRetrievalStatusAuthorityBoundary) throw InvalidResponse();
        var values = counts.ToDictionary(name => name, name => ParseBoundedNonNegativeInt(status, name, 65_536));
        var reviewState = ParseRequiredEnum(status, "reviewState", "draft", "held", "ready-for-human-review"); var state = ParseRequiredEnum(status, "state", "attention-required", "candidate-defined");
        var reasonsElement = status.GetProperty("reasons"); if (reasonsElement.ValueKind != JsonValueKind.Array || reasonsElement.GetArrayLength() > 2_048) throw InvalidResponse();
        var reasons = reasonsElement.EnumerateArray().Select(value => ParseSourceText(value, 2, 2_000)).ToArray(); if (state == "attention-required" && reasons.Length == 0) throw InvalidResponse();
        var assessedAt = ParseRequiredTimestamp(status, "assessedAt"); var candidateReference = ParseBusinessReference(status, "candidate");
        if (status.TryGetProperty("dependencies", out var dependencies)) {
            if (!HasOnlyProperties(dependencies, "designApplicability", "finalizedFigmaSnapshotImport", "humanDesignApproval", "designBaseline", "designToRequirementBinding", "designToCodeBindingRegistry", "routeScreenComponentMapping", "proposedChangePreview", "stagingWorkspace", "modelSwitchImplementation")) throw InvalidResponse();
            foreach (var property in dependencies.EnumerateObject()) { var reference = property.Value; if (!HasOnlyProperties(reference, "recordId", "revision", "digest")) throw InvalidResponse(); ParseRequiredGuid(reference, "recordId"); ParsePositiveLong(reference, "revision"); ParseRequiredDigest(reference, "digest"); }
        }
        ApprovedFigmaContextRetrievalRecordView? candidate = null;
        if (projection.TryGetProperty("candidate", out var value)) {
            if (!HasOnlyProperties(value, "id", "revision", "digest", "state", "approvedSnapshot", "generationContext", "lifecycle", "dependencyReceiptDigest", "approvedSnapshotReceiptDigest", "generationContextReceiptDigest", "lifecycleReceiptDigest", "assessmentReceiptDigest", "reviewState", "updatedAt") || ParseRequiredEnum(value, "state", "candidate") != "candidate") throw InvalidResponse();
            var id = ParseRequiredGuid(value, "id"); var revision = ParsePositiveLong(value, "revision"); var digest = ParseRequiredDigest(value, "digest"); if (!Matches(candidateReference, id, revision, digest)) throw InvalidResponse();
            var approved = value.GetProperty("approvedSnapshot"); if (!HasOnlyProperties(approved, "externalFileIdentityDigest", "returnedExternalVersionDigest", "itemCatalogDigest", "itemCount", "includedItemCount", "excludedItemCount", "approvalSubjectDigest", "approvalScopeDigest", "humanDecisionReceiptDigest", "humanDecisionCandidateState", "baselineMembershipDigest", "baselineLineageId", "baselineCandidateSetId", "baselineCandidateSetRevision", "baselineSemanticVersion")) throw InvalidResponse();
            foreach (var name in new[] { "externalFileIdentityDigest", "returnedExternalVersionDigest", "itemCatalogDigest", "approvalSubjectDigest", "approvalScopeDigest", "humanDecisionReceiptDigest", "baselineMembershipDigest" }) ParseRequiredDigest(approved, name);
            ParseRequiredGuid(approved, "baselineLineageId"); ParseRequiredGuid(approved, "baselineCandidateSetId"); ParsePositiveLong(approved, "baselineCandidateSetRevision"); if (ParseRequiredEnum(approved, "humanDecisionCandidateState", "approved-candidate") != "approved-candidate") throw InvalidResponse();
            var itemCount = ParseBoundedNonNegativeInt(approved, "itemCount", 33_792); var includedItemCount = ParseBoundedNonNegativeInt(approved, "includedItemCount", 33_792); var excluded = ParseBoundedNonNegativeInt(approved, "excludedItemCount", 33_792); if (includedItemCount == 0 || includedItemCount + excluded != itemCount) throw InvalidResponse();
            var generation = value.GetProperty("generationContext"); if (!HasOnlyProperties(generation, "designApplicabilityMembershipDigest", "requirementBindingMembershipDigest", "designToCodeBindingMembershipDigest", "routeSubjectCatalogDigest", "routeRelationshipCatalogDigest", "previewAssessmentDigest", "stagingAssessmentDigest", "modelSwitchAssessmentDigest", "requirementBindingCount", "designToCodeBindingCount", "routeSubjectCount", "routeRelationshipCount", "implementationUnitCount", "pathCount", "contentBoundary", "materializationState", "transferState")) throw InvalidResponse();
            foreach (var name in new[] { "designApplicabilityMembershipDigest", "requirementBindingMembershipDigest", "designToCodeBindingMembershipDigest", "routeSubjectCatalogDigest", "routeRelationshipCatalogDigest", "previewAssessmentDigest", "stagingAssessmentDigest", "modelSwitchAssessmentDigest" }) ParseRequiredDigest(generation, name);
            var contentBoundary = ParseRequiredEnum(generation, "contentBoundary", "metadata-and-digests-only"); var materialization = ParseRequiredEnum(generation, "materializationState", "not-performed"); var transfer = ParseRequiredEnum(generation, "transferState", "not-performed");
            var lifecycle = value.GetProperty("lifecycle"); if (!HasOnlyProperties(lifecycle, "retrievalCandidateState", "figmaConnectionState", "remoteFetchState", "contextMaterializationState", "contextTransferState", "generationState", "providerExecutionState", "stageEffectState", "sourceMutationState", "approvalState", "authorizationState", "acceptanceState")) throw InvalidResponse();
            string Exact(string name, string expected) { var result = ParseRequiredEnum(lifecycle, name, expected); if (result != expected) throw InvalidResponse(); return result; }
            Exact("retrievalCandidateState", "candidate-defined"); var figma = Exact("figmaConnectionState", "not-performed"); var fetch = Exact("remoteFetchState", "not-performed"); var contextMaterialization = Exact("contextMaterializationState", "not-performed"); var contextTransfer = Exact("contextTransferState", "not-performed"); var generationState = Exact("generationState", "not-performed"); var provider = Exact("providerExecutionState", "not-performed"); var stage = Exact("stageEffectState", "not-performed"); var mutation = Exact("sourceMutationState", "not-performed"); Exact("approvalState", "not-established"); Exact("authorizationState", "not-established"); Exact("acceptanceState", "not-established");
            foreach (var name in new[] { "dependencyReceiptDigest", "approvedSnapshotReceiptDigest", "generationContextReceiptDigest", "lifecycleReceiptDigest", "assessmentReceiptDigest" }) ParseRequiredDigest(value, name);
            candidate = new(id, revision, digest, ParseSourceText(approved.GetProperty("baselineSemanticVersion"), 1, 128), ParseRequiredDigest(approved, "returnedExternalVersionDigest"), itemCount, includedItemCount, contentBoundary, materialization, transfer, figma, fetch, contextMaterialization, contextTransfer, generationState, provider, stage, mutation, ParseRequiredEnum(value, "reviewState", "draft", "held", "ready-for-human-review"));
            if (candidate.SnapshotItemCount != values["snapshotItemCount"] || candidate.IncludedItemCount != values["includedItemCount"] || candidate.ReviewState != reviewState) throw InvalidResponse(); ParseRequiredTimestamp(value, "updatedAt");
        }
        if ((candidateReference is null) != (candidate is null) || ParseRequiredTimestamp(projection, "observedAt") != assessedAt) throw InvalidResponse();
        if (state == "candidate-defined" && (candidate is null || reviewState != "ready-for-human-review" || reasons.Length != 0 || counts.Where(name => name is not ("snapshotItemCount" or "includedItemCount" or "requirementBindingCount" or "designToCodeBindingCount" or "routeSubjectCount" or "implementationUnitCount" or "pathCount")).Sum(name => values[name]) > 0)) throw InvalidResponse();
        return new(productId, productRevision, productDigest, initiativeId, initiativeRevision, initiativeDigest, initiativeState, state, reviewState, Array.AsReadOnly(reasons), values["snapshotItemCount"], values["includedItemCount"], values["requirementBindingCount"], values["designToCodeBindingCount"], values["routeSubjectCount"], values["implementationUnitCount"], values["pathCount"], values["staleBindingCount"], values["snapshotGapCount"], values["generationContextGapCount"], values["lifecycleGapCount"], values["evidenceGapCount"], values["invalidCandidateCount"], values["unresolvedQuestionCount"], candidate, snapshotDigest);
    }
}
