namespace Gaep.HostClient;

public sealed record DesignConflictResolutionDeltaBindingView(
    Guid RecordId,
    long Revision,
    string Digest,
    string MembershipDigest,
    string DeltaCatalogDigest,
    string ComparisonReceiptDigest,
    int ConflictingCount,
    string CandidateResult,
    string ReviewState);

public sealed record DesignConflictResolutionRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    DesignConflictResolutionDeltaBindingView DesignDelta,
    string ResolutionDefinitionDigest,
    string ResolutionReceiptDigest,
    string ResolutionCatalogDigest,
    int ConflictCount,
    int ResolutionCount,
    string CoverageState,
    string ProvenanceState,
    string CandidateResult,
    string ReviewState);

public sealed record DesignConflictResolutionProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string CandidateResult,
    string ReviewState,
    string AssessmentState,
    string CoverageState,
    string ProvenanceState,
    IReadOnlyList<string> Reasons,
    int ConflictCount,
    int ResolutionCount,
    int AcceptSourceCount,
    int AcceptTargetCount,
    int MergeCount,
    int RejectChangeCount,
    int EscalateCount,
    int HumanReviewedCount,
    int DistinctActorDeclaredCount,
    int ExpiredCandidateCount,
    int UnresolvedConflictCount,
    int UnresolvedQuestionCount,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    DesignConflictResolutionRecordView? Candidate,
    string SnapshotDigest);
