namespace Gaep.HostClient;

public sealed record FigmaContextImportRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    int ContextPackCount,
    int SectionCount,
    int ContextItemCount,
    int TargetCount,
    int RepresentedRequirementCount,
    string ReviewState);

public sealed record FigmaContextImportProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string AssessmentState,
    string ReviewState,
    string ContextSelectionState,
    string ProvenanceState,
    string PreviewState,
    IReadOnlyList<string> Reasons,
    int ContextPackCount,
    int SectionCount,
    int ContextItemCount,
    int TargetCount,
    int HumanReviewedSectionCount,
    int SourceRecordedSectionCount,
    int NotAssessedSectionCount,
    int UnresolvedRedactionCount,
    int RepresentedRequirementCount,
    int UnresolvedRequirementCount,
    int UnresolvedOwnershipCount,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    int UnresolvedQuestionCount,
    FigmaContextImportRecordView? Candidate,
    string SnapshotDigest);
