namespace Gaep.HostClient;

public sealed record FigmaToBoilerplateMappingReference(Guid RecordId, long Revision, string Digest);

public sealed record FigmaToBoilerplateMappingRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MappingSubjectCatalogDigest,
    string TargetCatalogDigest,
    string TraceReceiptDigest,
    string MappingReceiptDigest,
    string AssessmentReceiptDigest,
    int SubjectCount,
    int MappedCandidateCount,
    int ConflictCandidateCount,
    int UnmappedCandidateCount,
    int NotAssessedCount,
    string ReviewState);

public sealed record FigmaToBoilerplateMappingProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string State,
    string ReviewState,
    IReadOnlyList<string> Reasons,
    IReadOnlyDictionary<string, FigmaToBoilerplateMappingReference> Dependencies,
    int DesignBindingCount,
    int SubjectCount,
    int MappedCandidateCount,
    int ConflictCandidateCount,
    int UnmappedCandidateCount,
    int NotAssessedCount,
    int ComponentMappingCount,
    int TokenMappingCount,
    int LayoutMappingCount,
    int ResponsiveBehaviorMappingCount,
    int PlatformTargetMappingCount,
    int MissingSubjectCount,
    int InvalidSubjectCount,
    int TargetGapCount,
    int TraceGapCount,
    int EvidenceGapCount,
    int StaleBindingCount,
    int StaleDependencyCount,
    int InvalidCandidateCount,
    int UnresolvedQuestionCount,
    FigmaToBoilerplateMappingRecordView? Candidate,
    string SnapshotDigest);
