namespace Gaep.HostClient;

public sealed record FigmaMcpCapabilityDiscoveryRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    int ToolCount,
    int AdvertisedToolCount,
    int ReadToolCount,
    int WriteToolCount,
    string ReviewState);

public sealed record FigmaMcpCapabilityDiscoveryProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string AssessmentState,
    string ReviewState,
    string CatalogState,
    string PermissionModelState,
    string LimitCatalogState,
    string VersionCatalogState,
    IReadOnlyList<string> Reasons,
    int ToolCount,
    int AdvertisedToolCount,
    int UnavailableToolCount,
    int UnknownAvailabilityCount,
    int ReadToolCount,
    int WriteToolCount,
    int UnknownEffectCount,
    int NotAssessedToolCount,
    int SourceRecordedToolCount,
    int HumanReviewedToolCount,
    int UnresolvedPermissionCount,
    int UnresolvedLimitCount,
    int UnresolvedVersionCount,
    int UnresolvedOwnershipCount,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    int UnresolvedQuestionCount,
    FigmaMcpCapabilityDiscoveryRecordView? Candidate,
    string SnapshotDigest);
