namespace Gaep.HostClient;

public sealed record MvpSliceDefinitionRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    string HierarchyDigest,
    int ScopeNodeCount,
    int MvpNodeCount,
    int LaterNodeCount,
    int ExcludedNodeCount,
    int SliceCount,
    int StoryCount,
    int TaskCount,
    string ReviewState);

public sealed record MvpSliceDefinitionProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string AssessmentState,
    string ReviewState,
    string ScopeCompletenessState,
    IReadOnlyList<string> Reasons,
    Guid? HierarchyRecordId,
    long? HierarchyRevision,
    string? HierarchyDigest,
    int ScopeNodeCount,
    int MvpNodeCount,
    int LaterNodeCount,
    int ExcludedNodeCount,
    int SliceCount,
    int StoryCount,
    int TaskCount,
    int DependencyCount,
    int UnassignedMvpStoryTaskCount,
    int StaleBindingCount,
    int StaleHierarchyCount,
    int InvalidScopeCount,
    int InvalidSliceCount,
    int UnresolvedQuestionCount,
    MvpSliceDefinitionRecordView? Candidate,
    string SnapshotDigest);
