namespace Gaep.HostClient;

public sealed record P0P4ReadinessGateRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    string EvaluationDefinitionDigest,
    int OutputCount,
    int WaiverCount,
    int UnresolvedDecisionCount,
    int ConditionCount);

public sealed record P0P4ReadinessGateProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string Result,
    IReadOnlyList<string> Reasons,
    int OutputCount,
    int ApplicableOutputCount,
    int NotApplicableOutputCount,
    int UnresolvedApplicabilityCount,
    int SatisfiedOutputCount,
    int ConditionalOutputCount,
    int IncompleteOutputCount,
    int FailedOutputCount,
    int BlockedOutputCount,
    int StaleOrUnknownOutputCount,
    int PendingOrInvalidWaiverCount,
    int UnresolvedDecisionCount,
    int UnmetConditionCount,
    int UnresolvedRequirementCount,
    int AdverseEvidenceCount,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    int InconsistencyCount,
    int UnresolvedQuestionCount,
    string GateBoundary,
    P0P4ReadinessGateRecordView? Gate,
    string SnapshotDigest);
