namespace Gaep.HostClient;

public sealed record Phase2UxFigmaDashboardSource(
    string Id,
    string Title,
    string Group,
    string ProjectionKind,
    string Availability,
    string? AssessmentState);

public sealed record Phase2UxFigmaDashboard(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string PhaseState,
    int CurrentSourceCount,
    int AttentionRequiredSourceCount,
    int UnavailableSourceCount,
    int PersonaCount,
    int DesignRoleCount,
    int JourneyCount,
    int ScreenCount,
    int StateCount,
    int RequirementCount,
    int TokenCount,
    int ComponentCount,
    int AccessibilityRuleCount,
    int FigmaFileCount,
    int DesignBindingCount,
    string FigmaConnectionState,
    string FigmaWriteExecutionState,
    string FigmaImportExecutionState,
    int DriftObservationCount,
    int DriftCount,
    int UnassessedDriftCount,
    int RemediationCandidateCount,
    string FreshnessState,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    int UnresolvedQuestionCount,
    IReadOnlyList<Phase2UxFigmaDashboardSource> Sources,
    IReadOnlyList<string> Limitations,
    string SnapshotDigest);
