namespace Gaep.HostClient;

public sealed record ResponsiveMultiPlatformTargetsRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string MembershipDigest,
    int PlatformTargetCount,
    int BreakpointCount,
    int BehaviorCount,
    int CheckCount,
    int RepresentedRequirementCount,
    string ReviewState);

public sealed record ResponsiveMultiPlatformTargetsProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string AssessmentState,
    string ReviewState,
    string TargetCatalogState,
    string BreakpointCatalogState,
    string BehaviorCatalogState,
    IReadOnlyList<string> Reasons,
    int PlatformTargetCount,
    int BreakpointCount,
    int BehaviorCount,
    int CheckCount,
    int ApplicableBehaviorCount,
    int UnresolvedBehaviorCount,
    int NotAssessedCheckCount,
    int EvidenceRecordedCheckCount,
    int HumanReviewedCheckCount,
    int ContradictedCheckCount,
    int RepresentedRequirementCount,
    int UnresolvedRequirementCount,
    int UnresolvedOwnershipCount,
    int StaleBindingCount,
    int StaleSourceReferenceCount,
    int UnresolvedQuestionCount,
    ResponsiveMultiPlatformTargetsRecordView? Candidate,
    string SnapshotDigest);
