namespace Gaep.HostClient;

public sealed record RouteScreenComponentMappingReference(Guid RecordId, long Revision, string Digest);

public sealed record RouteScreenComponentMappingRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string SubjectCatalogDigest,
    string RelationshipCatalogDigest,
    string TraceReceiptDigest,
    string MappingReceiptDigest,
    string AssessmentReceiptDigest,
    int SubjectCount,
    int RouteSubjectCount,
    int ScreenSubjectCount,
    int StateSubjectCount,
    int ComponentSubjectCount,
    int MappedCandidateCount,
    int ConflictCandidateCount,
    int UnmappedCandidateCount,
    int NotAssessedCount,
    int RelationshipCount,
    int DefinedRelationshipCount,
    string ReviewState);

public sealed record RouteScreenComponentMappingProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string State,
    string ReviewState,
    IReadOnlyList<string> Reasons,
    IReadOnlyDictionary<string, RouteScreenComponentMappingReference> Dependencies,
    int SourceRouteCount,
    int SourceScreenCount,
    int SourceStateCount,
    int SourceComponentCount,
    int SubjectCount,
    int RouteSubjectCount,
    int ScreenSubjectCount,
    int StateSubjectCount,
    int ComponentSubjectCount,
    int MappedCandidateCount,
    int ConflictCandidateCount,
    int UnmappedCandidateCount,
    int NotAssessedCount,
    int RelationshipCount,
    int DefinedRelationshipCount,
    int ConflictRelationshipCount,
    int NotAssessedRelationshipCount,
    int MissingSubjectCount,
    int ExtraSubjectCount,
    int InvalidSubjectCount,
    int MissingRelationshipCount,
    int InvalidRelationshipCount,
    int TraceGapCount,
    int EvidenceGapCount,
    int ComponentPlacementGapCount,
    int TestHookGapCount,
    int StaleBindingCount,
    int StaleDependencyCount,
    int InvalidCandidateCount,
    int UnresolvedQuestionCount,
    RouteScreenComponentMappingRecordView? Candidate,
    string SnapshotDigest);
