namespace Gaep.HostClient;

public sealed record TestInventoryReference(Guid RecordId, long Revision, string Digest);

public sealed record TestInventoryRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string CatalogReceiptDigest,
    string CoverageReceiptDigest,
    string TraceReceiptDigest,
    string OwnershipReceiptDigest,
    string AssessmentReceiptDigest,
    int AssetCount,
    int CatalogedAssetCount,
    int ConflictAssetCount,
    int ObservedAssetCount,
    int PlannedAssetCount,
    string ReviewState);

public sealed record TestInventoryProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string State,
    string ReviewState,
    IReadOnlyList<string> Reasons,
    IReadOnlyDictionary<string, TestInventoryReference> Dependencies,
    int SourceCriterionCount,
    int SourceRiskCount,
    int SourceUnitCount,
    int SourceMappingSubjectCount,
    int SourceMethodologyScopeCount,
    int AssetCount,
    int CatalogedAssetCount,
    int ConflictAssetCount,
    int MissingAssetCount,
    int DeferredAssetCount,
    int NotAssessedAssetCount,
    int ObservedAssetCount,
    int PlannedAssetCount,
    int AutomatedAssetCount,
    int ManualAssetCount,
    int DuplicateIdentityCount,
    int OrphanAssetCount,
    int UncoveredCriterionCount,
    int UncoveredRiskCount,
    int UncoveredUnitCount,
    int UncoveredMappingSubjectCount,
    int UncoveredMethodologyScopeCount,
    int OwnershipGapCount,
    int TraceGapCount,
    int EvidenceGapCount,
    int StaleBindingCount,
    int StaleDependencyCount,
    int InvalidCandidateCount,
    int UnresolvedQuestionCount,
    TestInventoryRecordView? Candidate,
    string SnapshotDigest);
