namespace Gaep.HostClient;

public sealed record TestMethodologyReference(Guid RecordId, long Revision, string Digest);

public sealed record TestMethodologyRecordView(
    Guid Id,
    long Revision,
    string Digest,
    string ScopeCatalogDigest,
    string MethodologyReceiptDigest,
    string EnvironmentReceiptDigest,
    string DataPolicyReceiptDigest,
    string OwnershipReceiptDigest,
    string TraceReceiptDigest,
    string AssessmentReceiptDigest,
    int ScopeCount,
    int DecisionCount,
    int SelectedDecisionCount,
    int ConflictDecisionCount,
    int EnvironmentCount,
    int DataPolicyCount,
    int EvidenceExpectationCount,
    int EntryCriterionCount,
    int ExitCriterionCount,
    string ReviewState);

public sealed record TestMethodologyProjection(
    Guid ProductId,
    long ProductRevision,
    string ProductDigest,
    Guid InitiativeId,
    long InitiativeRevision,
    string InitiativeDigest,
    string InitiativeState,
    string State,
    string ReviewState,
    IReadOnlyList<string> Reasons,
    IReadOnlyDictionary<string, TestMethodologyReference> Dependencies,
    int SourceUnitCount,
    int SourceRequirementCount,
    int SourceCriterionCount,
    int SourceMappingSubjectCount,
    int ScopeCount,
    int DecisionCount,
    int SelectedDecisionCount,
    int ConflictDecisionCount,
    int NotApplicableDecisionCount,
    int DeferredDecisionCount,
    int NotAssessedDecisionCount,
    int EnvironmentCount,
    int DataPolicyCount,
    int EvidenceExpectationCount,
    int EntryCriterionCount,
    int ExitCriterionCount,
    int MissingScopeCount,
    int ExtraScopeCount,
    int InvalidDecisionCount,
    int EnvironmentGapCount,
    int DataPolicyGapCount,
    int OwnershipGapCount,
    int TraceGapCount,
    int EvidenceGapCount,
    int CriterionGapCount,
    int StaleBindingCount,
    int StaleDependencyCount,
    int InvalidCandidateCount,
    int UnresolvedQuestionCount,
    TestMethodologyRecordView? Candidate,
    string SnapshotDigest);
