import { randomUUID } from "node:crypto"
import { canonicalDigest } from "@gaep/agent-sdk"
import { localUatInputSchema, localUatProjectionSchema, localUatSchema, localUatStatusSchema, type BusinessContextBinding, type Initiative, type LocalUat, type LocalUatInput, type LocalUatProjection, type LocalUatStatus, type Product, type QaScorecard, type WorkspaceHealthIssue } from "@gaep/contracts"
import { z, type ZodType } from "zod"
import type { GaepRepository, MutationWrite } from "./repository.js"

type ExactReference = { recordId: string; revision: number; digest: string }
type CurrentReader<T> = { readCurrent(initiativeId: string): Promise<T | undefined> }
const uuidSchema = z.string().uuid(), currentPattern = /^[0-9a-f-]+\.json$/i, inventoryLimit = 10_000
const authorityBoundary = "local-uat-is-a-versioned-scenario-and-evidence-workflow-and-does-not-sign-for-a-human-establish-product-owner-acceptance-release-deployment-or-action-authority" as const
const statusBoundary = "local-uat-status-is-observational-and-grants-no-human-sign-off-product-owner-acceptance-release-deployment-or-action-authority" as const
const projectionBoundary = "local-uat-projection-is-read-only-and-grants-no-human-sign-off-product-owner-acceptance-release-deployment-or-action-authority" as const
const privacyBoundary = "projection-contains-scenario-step-count-outcome-evidence-digest-actor-id-sign-off-and-receipt-metadata-only-not-artifact-bytes-product-content-personal-data-secrets-credentials-permissions-or-machine-paths" as const
function revisionOf(value: { revision?: number }) { return value.revision ?? 1 }
function reference(value: { id: string; revision: number }): ExactReference { return { recordId: value.id, revision: value.revision, digest: canonicalDigest(value) } }
function same(referenceValue: ExactReference | undefined, value: { id: string; revision?: number } | undefined) { return Boolean(referenceValue && value && referenceValue.recordId === value.id && referenceValue.revision === revisionOf(value) && referenceValue.digest === canonicalDigest(value)) }

export class LocalUatService {
  constructor(private readonly repository: GaepRepository, private readonly readProduct: () => Promise<Product>, private readonly readInitiative: (id: string) => Promise<Initiative>, private readonly qaScorecards: CurrentReader<QaScorecard>) {}
  async create(inputValue: LocalUatInput, actorId: string): Promise<LocalUat> { const input = localUatInputSchema.parse(inputValue); return this.repository.withLock(async () => {
    await this.assertIntegrity(); const { product, initiative } = await this.mutable(input.initiativeId); this.context(input.context, product, initiative); const scorecard = await this.exactScorecard(input)
    if (await this.readCurrent(input.initiativeId)) throw new Error("A current local UAT candidate already exists; create a revision")
    const now = new Date().toISOString(), record = localUatSchema.parse({ schemaVersion: 1, kind: "local-uat-candidate", id: randomUUID(), productId: product.id, ...input, revision: 1, ...this.digests(input, scorecard), state: "candidate", createdBy: { kind: "human", id: actorId }, updatedBy: { kind: "human", id: actorId }, createdAt: now, updatedAt: now, authorityBoundary })
    await this.commit(record, "local-uat.created", actorId); return record }) }
  async revise(id: string, expectedRevision: number, inputValue: LocalUatInput, actorId: string): Promise<LocalUat> { const input = localUatInputSchema.parse(inputValue); return this.repository.withLock(async () => {
    await this.assertIntegrity(); const current = await this.read(id); if (current.revision !== expectedRevision) throw new Error("Local UAT revision conflict"); if (current.initiativeId !== input.initiativeId) throw new Error("Local UAT Initiative binding is immutable")
    const { product, initiative } = await this.mutable(input.initiativeId); this.context(input.context, product, initiative); const scorecard = await this.exactScorecard(input)
    const record = localUatSchema.parse({ ...current, ...input, revision: current.revision + 1, ...this.digests(input, scorecard), predecessorDigest: canonicalDigest(current), updatedBy: { kind: "human", id: actorId }, updatedAt: new Date().toISOString() }); await this.commit(record, "local-uat.revised", actorId); return record }) }
  async read(id: string) { return this.repository.readJson(this.currentPath(this.uuid(id, "Local UAT ID")), localUatSchema) }
  async readCurrent(initiativeId: string): Promise<LocalUat | undefined> { const target = this.uuid(initiativeId, "Initiative ID"), records = (await this.list("local-uat", currentPattern, localUatSchema)).filter((record) => record.initiativeId === target); if (records.length > 1) throw new Error("Multiple current local UAT candidates target one Initiative"); return records[0] }
  async readRevision(id: string, revision: number) { const recordId = this.uuid(id, "Local UAT ID"); if (!Number.isInteger(revision) || revision < 1) throw new Error("Revision must be positive"); const record = await this.repository.readJson(this.historyPath(recordId, revision), localUatSchema); if (record.id !== recordId || record.revision !== revision) throw new Error("Local UAT history binding mismatch"); return record }
  async listHistory(id: string) { const recordId = this.uuid(id, "Local UAT ID"); return (await this.list("local-uat-history", new RegExp(`^local-uat-${recordId}-r[1-9][0-9]*\\.json$`, "i"), localUatSchema)).sort((a, b) => b.revision - a.revision) }
  async assess(initiativeId: string): Promise<LocalUatStatus> { const target = this.uuid(initiativeId, "Initiative ID"), [product, initiative, candidate, scorecard] = await Promise.all([this.readProduct(), this.readInitiative(target), this.readCurrent(target), this.qaScorecards.readCurrent(target)])
    const scenarios = candidate?.scenarios ?? [], count = (outcome: LocalUat["scenarios"][number]["outcome"]) => scenarios.filter((scenario) => scenario.outcome === outcome).length
    const pendingCount = count("pending"), passCount = count("pass"), failCount = count("fail"), notPerformedCount = count("not-performed"), staleBindingCount = candidate && !same(candidate.qaScorecard, scorecard) ? 1 : 0, reasons: string[] = []
    if (!candidate) reasons.push("No current local UAT candidate is recorded"); if (staleBindingCount) reasons.push("The exact QA scorecard binding is stale"); if (pendingCount) reasons.push("One or more UAT scenarios await human validation"); if (failCount) reasons.push("One or more UAT scenarios failed"); if (notPerformedCount) reasons.push("One or more UAT scenarios were not performed")
    const unresolvedQuestionCount = candidate?.unresolvedQuestionKeys.length ?? 0; if (unresolvedQuestionCount) reasons.push("The UAT workflow contains unresolved questions")
    const evidenceCount = candidate?.evidence.length ?? 0, signOffState = candidate?.signOff.state ?? "pending"
    const state = candidate && !staleBindingCount && failCount + notPerformedCount + unresolvedQuestionCount === 0 && passCount === scenarios.length && signOffState !== "pending" ? "human-validation-recorded" : candidate && !staleBindingCount && failCount + notPerformedCount === 0 ? "awaiting-human-validation" : "attention-required"
    return localUatStatusSchema.parse({ schemaVersion: 1, kind: "local-uat-status", productId: product.id, productRevision: revisionOf(product), initiativeId: initiative.id, initiativeRevision: revisionOf(initiative), ...(candidate ? { candidate: reference(candidate), qaScorecard: candidate.qaScorecard } : {}), scenarioCount: scenarios.length, pendingCount, passCount, failCount, notPerformedCount, evidenceCount, unresolvedQuestionCount, staleBindingCount, signOffState, state, reasons, assessedAt: new Date().toISOString(), authorityBoundary: statusBoundary }) }
  async project(initiativeId: string): Promise<LocalUatProjection> { const target = this.uuid(initiativeId, "Initiative ID"), [product, initiative, status, candidate] = await Promise.all([this.readProduct(), this.readInitiative(target), this.assess(target), this.readCurrent(target)])
    const body = { schemaVersion: 1 as const, kind: "local-uat-projection" as const, product: { id: product.id, revision: revisionOf(product), digest: canonicalDigest(product) }, initiative: { id: initiative.id, revision: revisionOf(initiative), digest: canonicalDigest(initiative), state: initiative.state }, status,
      ...(candidate ? { candidate: { id: candidate.id, revision: candidate.revision, digest: canonicalDigest(candidate), scenarios: candidate.scenarios.map((scenario) => ({ id: scenario.id, scenarioKey: scenario.scenarioKey, title: scenario.title, stepCount: scenario.steps.length, outcome: scenario.outcome, evidenceCount: scenario.evidenceIds.length, limitationCount: scenario.limitationKeys.length })), signOff: candidate.signOff, scenarioReceiptDigest: candidate.scenarioReceiptDigest, evidenceReceiptDigest: candidate.evidenceReceiptDigest, outcomeReceiptDigest: candidate.outcomeReceiptDigest, signOffReceiptDigest: candidate.signOffReceiptDigest, assessmentReceiptDigest: candidate.assessmentReceiptDigest, reviewState: candidate.reviewState, updatedAt: candidate.updatedAt } } : {}), observedAt: status.assessedAt, privacyBoundary, authorityBoundary: projectionBoundary }
    return localUatProjectionSchema.parse({ ...body, snapshotDigest: canonicalDigest(body) }) }
  async healthIssues(): Promise<WorkspaceHealthIssue[]> { const issues: WorkspaceHealthIssue[] = []; for (const candidate of await this.list("local-uat", currentPattern, localUatSchema)) { try { const history = await this.listHistory(candidate.id); if (history.length !== candidate.revision || canonicalDigest(history[0]) !== canonicalDigest(candidate)) throw new Error("Current UAT does not match immutable history"); if ((await this.assess(candidate.initiativeId)).state !== "human-validation-recorded") issues.push({ code: "local-uat.validation-pending", severity: "warning", message: `Initiative ${candidate.initiativeId} has pending, failed, not-performed, stale, unresolved or unsigned UAT.`, record: { type: candidate.kind, id: candidate.id, revision: candidate.revision }, repairActions: ["inspect-read-only", "create-superseding-revision"] }) } catch (error) { issues.push({ code: "local-uat.invalid", severity: "error", message: `Local UAT ${candidate.id}: ${error instanceof Error ? error.message : "validation failed"}`, record: { type: candidate.kind, id: candidate.id, revision: candidate.revision }, repairActions: ["inspect-read-only", "manual-repair-required"] }) } } return issues }
  private async exactScorecard(input: LocalUatInput) { const scorecard = await this.qaScorecards.readCurrent(input.initiativeId); if (!same(input.qaScorecard, scorecard)) throw new Error("Local UAT must reference the exact current QA scorecard"); if (!scorecard || scorecard.productId === undefined) throw new Error("Current QA scorecard is unavailable"); return scorecard }
  private digests(input: LocalUatInput, scorecard: QaScorecard) { const scenarioReceiptDigest = canonicalDigest(input.scenarios.map(({ steps: _steps, evidenceIds: _evidence, ...scenario }) => scenario)), evidenceReceiptDigest = canonicalDigest(input.evidence), outcomeReceiptDigest = canonicalDigest(input.scenarios.map((scenario) => ({ id: scenario.id, outcome: scenario.outcome, steps: scenario.steps.map((step) => ({ id: step.id, outcome: step.outcome, evidenceIds: step.evidenceIds })) }))), signOffReceiptDigest = canonicalDigest(input.signOff), assessmentReceiptDigest = canonicalDigest({ qaScorecard: reference(scorecard), scenarioReceiptDigest, evidenceReceiptDigest, outcomeReceiptDigest, signOffReceiptDigest, unresolvedQuestionKeys: input.unresolvedQuestionKeys, reviewState: input.reviewState, humanValidationState: input.humanValidationState, productOwnerAcceptanceState: input.productOwnerAcceptanceState, releaseReadinessState: input.releaseReadinessState, actionAuthorityState: input.actionAuthorityState }); return { scenarioReceiptDigest, evidenceReceiptDigest, outcomeReceiptDigest, signOffReceiptDigest, assessmentReceiptDigest } }
  private context(binding: BusinessContextBinding, product: Product, initiative: Initiative) { if (initiative.productId !== product.id || canonicalDigest(binding) !== canonicalDigest({ productRevision: revisionOf(product), productDigest: canonicalDigest(product), initiativeRevision: revisionOf(initiative), initiativeDigest: canonicalDigest(initiative) })) throw new Error("Local UAT must bind exact current Product and Initiative") }
  private async mutable(initiativeId: string) { const [product, initiative] = await Promise.all([this.readProduct(), this.readInitiative(this.uuid(initiativeId, "Initiative ID"))]); if (initiative.productId !== product.id) throw new Error("Initiative does not target current Product"); if (["completed", "cancelled"].includes(initiative.state)) throw new Error("Terminal Initiative UAT is immutable"); return { product, initiative } }
  private async commit(record: LocalUat, eventType: string, actorId: string) { await this.repository.commitMutation({ writes: [this.governed(this.currentPath(record.id), record, localUatSchema), this.governed(this.historyPath(record.id, record.revision), record, localUatSchema)], audit: { eventType, actor: { kind: "human", id: actorId }, subjectId: record.id, payload: { initiativeId: record.initiativeId, revision: record.revision, recordDigest: canonicalDigest(record), qaScorecard: record.qaScorecard, scenarioCount: record.scenarios.length, evidenceCount: record.evidence.length, signOffState: record.signOff.state, humanValidationState: record.humanValidationState, productOwnerAcceptanceState: record.productOwnerAcceptanceState, actionAuthorityState: record.actionAuthorityState, authorityBoundary: record.authorityBoundary } } }) }
  private currentPath(id: string) { return this.repository.resolve("local-uat", `${id}.json`) } private historyPath(id: string, revision: number) { return this.repository.resolve("local-uat-history", `local-uat-${id}-r${revision}.json`) }
  private governed<T>(path: string, value: T, schema: ZodType<T>): MutationWrite<T> { return { path, value, schema, governed: true } } private uuid(value: string, label: string) { const parsed = uuidSchema.safeParse(value); if (!parsed.success) throw new Error(`${label} must be a UUID`); return parsed.data }
  private async assertIntegrity() { const value = await this.repository.verifyAudit(); if (!value.valid) throw new Error(value.error ?? "Audit invalid") }
  private async list<T>(directory: string, pattern: RegExp, schema: ZodType<T>): Promise<T[]> { let names: string[]; try { names = (await this.repository.readDirectory(this.repository.resolve(directory))).filter((name) => pattern.test(name)) } catch (error) { if (error instanceof Error && "code" in error && error.code === "ENOENT") return []; throw error } if (names.length > inventoryLimit) throw new Error("Local UAT inventory exceeds safety limit"); return Promise.all(names.map((name) => this.repository.readJson(this.repository.resolve(directory, name), schema))) }
}
